version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    ports:
    - "8010:5432"
  server:
    environment:
    - appoption=server
    build:
      context: .
    ports:
    - "8000:8000"
    depends_on:
    - db
    stdin_open: true
    tty: true
  client:
    environment:
      - appoption=client
    build:
      context: .
    stdin_open: true
    tty: true
