version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    ports:
    - "5432:5432"
  naming_server:
    environment:
    - appoption=naming_server
    build:
      context: .
    ports:
    - "2224"
    - "2000"
    stdin_open: true
    tty: true
    depends_on:
    - db
  server:
    environment:
    - appoption=server
    build:
      context: .
    ports:
    - "2000"
    - "2224"
    depends_on:
    - naming_server
  client:
    environment:
      - appoption=client
    build:
      context: .
    ports:
    - "2000"
    - "2224"
    stdin_open: true
    tty: true
    depends_on:
      - server
